### ISSUE TITLE
-ltcmalloc

### ISSUE THREAD

**Issue by rurban** [jzimmerman/langcc#1]
I hid this behind a macro, so I can build with `make LIBTCMALLOC=`

[tcmalloc.patch.gz](https://github.com/jzimmerman/langcc/files/9633043/tcmalloc.patch.gz)

libtcmalloc is in libgoogle-perftools-dev

**Comment by jzimmerman** [comment]
Generalized Makefile in commit ec3d63a (variable is called LFLAGS_TCMALLOC, instead of LIBTCMALLOC).

Note also that disabling tcmalloc might affect performance.
