### ISSUE TITLE
Wishlist: makefile portability

### ISSUE THREAD

**Issue by jddurand** [jzimmerman/langcc#28]
Proposal is to use cmake.

I have forked your repo and started working on that.

**Comment by jddurand** [comment]
This portability issue include also compiler portability, in particular Windows compilers (cl and borland at least) that definitely do not support GNU extensions e.g. ```__attribute__((noinline))```

**Comment by jzimmerman** [comment]
I would rather not switch to CMake, as the makefile has been working fine so far. Are there specific portability issues you have identified? (Other than Windows support - which would require other changes, and which I consider to be out of scope for the present time.)

**Comment by jddurand** [comment]
My interest was to built langcc using cl, not clang-cl, and to be frank the dependency of langcc on llvm is a blocker for me.
In conclusion I will not be able to answer the question and closes this issue.
