### ISSUE TITLE
Reduced stack activity for flattened recursive operations.

### ISSUE THREAD

**Issue by modulovalue** [jzimmerman/langcc#49]
The flattening procedure in the paper proposes a right recursive definition of the star operator (`a*` -> `B -> a B | ε`).

However, left recursive definitions (i.e., `B -> B a | ε`) are known to have reduced stack activity when it comes to LR-style parsers and should lead to more performant parsers.

The CPS transformation step appears to rely on the right recursive definition. (Construction 3.3, third case, first subcase)

I feel like, the CPS approach combined with the approach found in https://github.com/jzimmerman/langcc/issues/44 could allow for a left recursive definition. Data could be stored during the flattening procedure, which could be used to guide the CPS-transformation.

**Comment by modulovalue** [comment]
Because langcc appears to be abandoned, I'm going to close this issue.

**Comment by mingodad** [comment]
It's sad that you've closed several valid issues like this one, new comers will not be aware of the gotchas like this one and will loose time rediscovering it again like I did now.

**I would prefer that your pointed issues remain open.**
