### ISSUE TITLE
Enable GitHub Discussions for repo

### ISSUE THREAD

**Issue by sirinath** [jzimmerman/langcc#5]
I think it would be a good idea to enable GitHub discussions. Also perhaps have chat channel.

Also maybe this can be moved to an GtiHub org of its own.

**Comment by jzimmerman** [comment]
I've just enabled GitHub discussions. There may be a chat channel later, but not at the moment.

**Comment by sirinath** [comment]
Great!

What about moving this to own Org and perhaps having at least a basic website. The website can be done on GitHub pages. Hopefully this will help gain more attention and exposure to this project.
