### ISSUE TITLE
Arch linux support

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [jzimmerman/langcc#6]
Hey, 

Trying to get it running on arch linux, these are changes so far:

1. Here is my shell script for Arch deps:
```sh
#!/bin/bash
set -e
set -u
sudo pacman -S llvm crypto++ gperftools
```

2. Arch has different path than Ubuntu (and same as MacOS)
langcc_util.hpp
```hpp
#include <cryptopp/sha.h>
```
---

There is some linking issues that I have to little experience to solve quickly, so maybe you can see yourself quickly if it is for example https://archlinux.org/packages/extra/x86_64/llvm/ (flagged as outdated as there is v15 out) or something else I need to change to get it working.

```
$ make -j8

mkdir -p build
mkdir -p build
mkdir -p build
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -c -o build/datacc_main.o src/datacc_main.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -c -o build/datacc.o src/datacc.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -c -o build/cc__gen.o gen/cc__gen.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -c -o build/data__gen.o gen/data__gen.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -o build/datacc build/datacc_main.o build/datacc.o build/cc__gen.o build/data__gen.o  -L/usr/lib/llvm-14/lib -lLLVMSymbolize -lLLVMDemangle -lLLVMSupport -lcryptopp -lncurses -ltcmalloc
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64/libLLVMSymbolize.a(SymbolizableObjectFile.cpp.o): in function `llvm::symbolize::SymbolizableObjectFile::getModulePreferredBase() const [clone .localalias]':
(.text._ZNK4llvm9symbolize22SymbolizableObjectFile22getModulePreferredBaseEv+0x10): undefined reference to `llvm::object::COFFObjectFile::getImageBase() const'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64/libLLVMSymbolize.a(SymbolizableObjectFile.cpp.o): in function `llvm::symbolize::SymbolizableObjectFile::addCoffExportSymbols(llvm::object::COFFObjectFile const*) [clone .localalias]':
(.text._ZN4llvm9symbolize22SymbolizableObjectFile20addCoffExportSymbolsEPKNS_6object14COFFObjectFileE+0x5e): undefined reference to `llvm::object::COFFObjectFile::export_directories() const'
/usr/bin/ld: (.text._ZN4llvm9symbolize22SymbolizableObjectFile20addCoffExportSymbolsEPKNS_6object14COFFObjectFileE+0xbb): undefined reference to `llvm::object::ExportDirectoryEntryRef::moveNext()'
/usr/bin/ld: (.text._ZN4llvm9symbolize22SymbolizableObjectFile20addCoffExportSymbolsEPKNS_6object14COFFObjectFileE+0xc7): undefined reference to `llvm::object::ExportDirectoryEntryRef::operator==(llvm::object::ExportDirectoryEntryRef const&) const'
/usr/bin/ld: (.text._ZN4llvm9symbolize22SymbolizableObjectFile20addCoffExportSymbolsEPKNS_6object14COFFObjectFileE+0xf7): undefined reference to `llvm::object::ExportDirectoryEntryRef::getSymbolName(llvm::StringRef&) const'
/usr/bin/ld: (.text._ZN4llvm9symbolize22SymbolizableObjectFile20addCoffExportSymbolsEPKNS_6object14COFFObjectFileE+0x116): undefined reference to `llvm::object::ExportDirectoryEntryRef::getExportRVA(unsigned int&) const'
/usr/bin/ld: (.text._ZN4llvm9symbolize22SymbolizableObjectFile20addCoffExportSymbolsEPKNS_6object14COFFObjectFileE+0x258): undefined reference to `llvm::object::COFFObjectFile::getImageBase() const'
/usr/bin/ld: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64/libLLVMSymbolize.a(SymbolizableObjectFile.cpp.o): in function `llvm::symbolize::SymbolizableObjectFile::create(llvm::object::ObjectFile const*, std::unique_ptr<llvm::DIContext, std::default_delete<llvm::DIContext> >, bool)':
(.text._ZN4llvm9symbolize22SymbolizableObjectFile6createEPKNS_6object10ObjectFileESt10unique_ptrINS_9DIContextESt14default_deleteIS7_EEb+0x9e): undefined reference to `llvm::object::computeSymbolSizes(llvm::object::ObjectFile const&)'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:134: build/datacc] Error 1
```

**Comment by jzimmerman** [comment]
Can you pull and try to build a fresh copy? I've already removed the dependency on libcrypto++.

**Comment by DanielMazurkiewicz** [comment]
> Can you pull and try to build a fresh copy? I've already removed the dependency on libcrypto++.

did that, so point 2 solved :-)

but linking problem remains

**Comment by sp00ck** [comment]
on fedora: 5.11.22-100.fc32.x86_64 #1 SMP Wed May 19 18:58:25 UTC 2021 x86_64 x86_64

mkdir -p build
mkdir -p build
mkdir -p build
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -c -o build/datacc_main.o src/datacc_main.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -c -o build/datacc.o src/datacc.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -c -o build/cc__gen.o gen/cc__gen.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -c -o build/data__gen.o gen/data__gen.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -I/usr/include/llvm-c-14 -I/usr/include/llvm-14 -o build/datacc build/datacc_main.o build/datacc.o build/cc__gen.o build/data__gen.o  -L/usr/lib/llvm-14/lib -lLLVMSymbolize -lLLVMDemangle -lLLVMSupport -lncurses -ltcmalloc
/usr/bin/ld: cannot find -ltcmalloc
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:140: build/datacc] Błąd 1


----
this same ;(

**Comment by jzimmerman** [comment]
I'm not sure about the error on Fedora (it looks like tcmalloc is not present)?

But for the error on Arch, could you try pulling and rebuilding a clean copy again? I've just pushed some changes that should remove the LLVM link dependency.

**Comment by DanielMazurkiewicz** [comment]
> But for the error on Arch, could you try pulling and rebuilding a clean copy again? I've just pushed some changes that should remove the LLVM link dependency.

Success!!! It does compile successfully now!
